[package]
name = "basic"
version = "0.1.0"
authors = ["Oleksii-Kshenskyi <oleksii.kshenskyi@outlook.com>"]
edition = "2018"

[[bin]]
name="basic"
path="src/strings.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
